// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGEw2tqLMZQs-Y3eqhwc5QFHhdwObe_cU',
    appId: '1:344979839373:web:4ae255405e8ef43d4c85c4',
    messagingSenderId: '344979839373',
    projectId: 'mango-sort-afbe9',
    authDomain: 'mango-sort-afbe9.firebaseapp.com',
    storageBucket: 'mango-sort-afbe9.firebasestorage.app',
    measurementId: 'G-MDMG12YWSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgBNNHc60cODEKC47OBKFZ6CQskp7eeVU',
    appId: '1:344979839373:android:d0ed31ba767624234c85c4',
    messagingSenderId: '344979839373',
    projectId: 'mango-sort-afbe9',
    storageBucket: 'mango-sort-afbe9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_E3qZGNFMrRrD6mOjrIPEwaUesDXdgSA',
    appId: '1:344979839373:ios:89a339c24aafb85b4c85c4',
    messagingSenderId: '344979839373',
    projectId: 'mango-sort-afbe9',
    storageBucket: 'mango-sort-afbe9.firebasestorage.app',
    iosBundleId: 'com.example.mangoSort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_E3qZGNFMrRrD6mOjrIPEwaUesDXdgSA',
    appId: '1:344979839373:ios:89a339c24aafb85b4c85c4',
    messagingSenderId: '344979839373',
    projectId: 'mango-sort-afbe9',
    storageBucket: 'mango-sort-afbe9.firebasestorage.app',
    iosBundleId: 'com.example.mangoSort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGEw2tqLMZQs-Y3eqhwc5QFHhdwObe_cU',
    appId: '1:344979839373:web:521fb95acdde55c04c85c4',
    messagingSenderId: '344979839373',
    projectId: 'mango-sort-afbe9',
    authDomain: 'mango-sort-afbe9.firebaseapp.com',
    storageBucket: 'mango-sort-afbe9.firebasestorage.app',
    measurementId: 'G-4H0EFK87F3',
  );
}
